### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by aakashrajput** [Pokemon-World/pokemon-world-server#4]
Plz guys help me i am stuck in aonething and its not running plz help me to run this thing thanx

**Comment by NeonLightPWO** [comment]
?

**Comment by aakashrajput** [comment]
I was trying to run pokemon qorld online again but cant so meed your help plz contact me on skype or whattsapp . Really need your help regarding this

**Comment by NeonLightPWO** [comment]
Its currently offline

**Comment by aakashrajput** [comment]
I know bro its ofline adam shut it doqned i dont know y . I have a domain so we can start the server run it their i just want to make pokemon world online as a base after setting up everything in new domain we will make it digimon showdown i will work on it . Plz help me to run pokemon world files on my domain then i will edit everything and change it into digimon . Email me aakashsingh1999@gmail.com

**Comment by NeonLightPWO** [comment]
Ahahahahahahaha no have a nice day if you want anything join discord https://discord.gg/2ZkAJ9S
